# Dictionary of attributes and associated skills
# Lists used in case personal skills choices are desired
attribs_to_skills = {
    "STR": [
        "Aircraft Mechanic",
        "Heavy Weapons",
        "Hunting Bow",
        "Mechanic",
        "Melee Combat",
        "Small Arms",
        "Thrown Weapon",
    ],
    "EDU": [
        "Biology",
        "Chemistry",
        "Civil Engineer",
        "Computer",
        "Geology",
        "Medical",
        "Metallurgy",
        "Meteorology",
        "Mining Engineer",
    ],
    "CON": [
        "Combat Engineer",
        "Horsemanship",
        "Motorcycle",
        "Mountaineering",
        "Parachute",
        "Scuba",
        "Swimming",
    ],
    "CHR": [
        "Disguise",
        "Instruction",
        "Interrogation",
        "Language",
        "Leadership",
        "Persuasion",
    ],
    "INT": [
        "Farming",
        "Fishing",
        "Foraging",
        "Forward Observer",
        "Navigation",
        "Observation",
        "Scrounging",
        "Tracking",
    ],
    "AGL": [
        "Electronics",
        "Forgery",
        "Gunsmith",
        "Lockpick",
        "Machinist",
        "Pilot",
        "Small Boat",
        "Snow Skiing",
        "Stealth",
        "Tracked Vehicle",
        "Warhead",
        "Wheeled Vehicle",
    ],
}
#  Alphabetical mapping of skills to attributes
skills_to_attribs = {
    "Aircraft Mechanic": "STR",
    "Biology": "EDU",
    "Chemistry": "EDU",
    "Civil Engineer": "EDU",
    "Combat Engineer": "CON",
    "Computer": "EDU",
    "Disguise": "CHR",
    "Electronics": "AGL",
    "Farming": "INT",
    "Fishing": "INT",
    "Foraging": "INT",
    "Forgery": "AGL",
    "Forward Observer": "INT",
    "Geology": "EDU",
    "Gunsmith": "AGL",
    "Heavy Weapons": "STR",
    "Horsemanship": "CON",
    "Hunting Bow": "STR",
    "Instruction": "CHR",
    "Interrogation": "CHR",
    "Language": "CHR",
    "Leadership": "CHR",
    "Lockpick": "AGL",
    "Machinist": "AGL",
    "Mechanic": "STR",
    "Medical": "EDU",
    "Melee Combat": "STR",
    "Metallurgy": "EDU",
    "Meteorology": "EDU",
    "Mining Engineer": "EDU",
    "Motorcycle": "CON",
    "Mountaineering": "CON",
    "Navigation": "INT",
    "Observation": "INT",
    "Parachute": "CON",
    "Persuasion": "CHR",
    "Pilot": "AGL",
    "Scrounging": "INT",
    "Scuba": "CON",
    "Small Arms": "STR",
    "Small Boat": "AGL",
    "Snow Skiing": "AGL",
    "Stealth": "AGL",
    "Swimming": "CON",
    "Thrown Weapon": "STR",
    "Tracked Vehicle": "AGL",
    "Tracking": "INT",
    "Warhead": "AGL",
    "Wheeled Vehicle": "AGL"
}
